version: 2
updates:
    # Fetch and update latest `npm` packages
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: daily
          time: '00:00'
      open-pull-requests-limit: 10
      ignore:
        - dependency-name: 'vue'
          versions: ['3.x']
        - dependency-name: '@nuxt/content'
          versions: ['2.x']
        - dependency-name: 'autoprefixer'
          versions: ['10.x']
        - dependency-name: 'postcss-preset-env'
          versions: ['7.x']
      commit-message:
          prefix: fix
          prefix-development: chore
          include: scope
    # Fetch and update latest `github-actions` pkgs
    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: daily
          time: '00:00'
      open-pull-requests-limit: 10
      reviewers:
          - ryan mulready
      assignees:
          - ryan mulready
      commit-message:
          prefix: fix
          prefix-development: chore
          include: scope
