name: login

inputs:
    aws-access-key-id:
        description: AWS Access Key ID
        required: true
    aws-secret-access-key:
        description: AWS Secret Key Secret
        required: true
    aws-region:
        description: AWS Region
        required: false
        default: us-east-1

runs:
    using: composite
    steps:
        - name: Log into ES_DS_DEV AWS account 🔑
          uses: aws-actions/configure-aws-credentials@v4
          with:
              aws-access-key-id: ${{ inputs.aws-access-key-id }}
              aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
              aws-region: ${{ inputs.aws-region }}
