name: ci

on:
    workflow_call:
    pull_request:
        branches:
            - main

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 🛎
              uses: actions/checkout@v4

            - name: Get nodenv version 🔌
              id: nodenv
              shell: bash
              run: echo "node-version=$(cat .node-version)" >> $GITHUB_OUTPUT

            - name: Setup node env 🏗
              uses: actions/setup-node@v4
              with:
                  node-version: '${{ steps.nodenv.outputs.node-version }}'
                  check-latest: true

            - name: Install dependencies 👨🏻‍💻
              run: |
                make install
                make symlink

            - name: Verify component symlink
              run: ls -la es-ds-docs/node_modules/@energysage/es-ds-components

            - name: Building
              run: make build

            - name: Run linter 👀
              run: make lint

            - name: Run typechecker
              run: make typecheck

            - name: Run tests 🧪
              run: make test
